import React, { useState } from 'react';
import DashboardLayout from '../../components/admin/DashboardLayout';
import { useNotification } from '../../context/NotificationContext';

const ForgePage: React.FC = () => {
    const [prompt, setPrompt] = useState('');
    const [generatedCode, setGeneratedCode] = useState<string | null>(null);
    const [isLoading, setIsLoading] = useState(false);
    const { addNotification } = useNotification();

    const handleGenerate = async () => {
        if (!prompt.trim()) {
            addNotification('Please describe the feature you want to build.', 'error');
            return;
        }
        setIsLoading(true);
        setGeneratedCode(null);
        
        // Mock API call
        setTimeout(() => {
            const mockCode = `
// Backend Route (Express.js)
router.get('/api/new-feature', (req, res) => {
  res.json({ message: 'This is a new feature!' });
});

// Frontend Component (React)
const NewFeatureComponent = () => (
  <div>
    <h1>New Feature</h1>
    <p>This component was generated by the Forge.</p>
  </div>
);
            `;
            setGeneratedCode(mockCode.trim());
            setIsLoading(false);
            addNotification('Cognitive Blueprint generated successfully!', 'success');
        }, 2000);
    };

    return (
        <DashboardLayout>
            <h1 className="text-3xl font-bold text-slate-800 dark:text-white mb-2">Whisspra Forge</h1>
            <p className="text-slate-500 dark:text-slate-400 mb-8">
                Generate new platform features using Cognitive Blueprints powered by Gemini. Describe your feature in the text area below.
            </p>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                {/* Input Section */}
                <div className="bg-white dark:bg-slate-800 p-6 rounded-lg shadow-md border border-slate-200 dark:border-slate-700">
                    <h2 className="text-xl font-semibold mb-4">Feature Description</h2>
                    <textarea
                        value={prompt}
                        onChange={(e) => setPrompt(e.target.value)}
                        placeholder="e.g., 'Create a polling system for group chats. Users can create a poll with multiple options, and other users can vote. Show real-time results.'"
                        className="w-full h-64 bg-slate-100 dark:bg-slate-700 p-3 rounded-md border border-slate-300 dark:border-slate-600 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                    />
                    <button
                        onClick={handleGenerate}
                        disabled={isLoading}
                        className="mt-4 w-full bg-indigo-500 hover:bg-indigo-600 text-white font-semibold py-3 rounded-lg transition-all disabled:opacity-50"
                    >
                        {isLoading ? 'Generating...' : 'Generate Blueprint'}
                    </button>
                </div>

                {/* Output Section */}
                <div className="bg-white dark:bg-slate-800 p-6 rounded-lg shadow-md border border-slate-200 dark:border-slate-700">
                    <h2 className="text-xl font-semibold mb-4">Generated Code</h2>
                    <div className="bg-slate-900 rounded-lg h-[21.5rem] p-4 overflow-y-auto">
                        {isLoading ? (
                            <div className="flex items-center justify-center h-full text-slate-400">
                                <svg className="animate-spin h-5 w-5 mr-3" viewBox="0 0 24 24">
                                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                </svg>
                                Generating...
                            </div>
                        ) : generatedCode ? (
                            <pre><code className="text-sm text-slate-300 whitespace-pre-wrap">{generatedCode}</code></pre>
                        ) : (
                            <p className="text-slate-500 text-center mt-20">Generated code will appear here.</p>
                        )}
                    </div>
                </div>
            </div>
        </DashboardLayout>
    );
};

export default ForgePage;
